passwords:
titles:
  join:
    title: §6Sunucuya Hoş Geldin
    subtitle: §2play§6.§1ocean§3monster§6.§4net
    fadein: 20
    stay: 20
    fadeout: 20
  register:
    title: §c/register §8şifre §7şifre
    subtitle: Sunucuda oynayabilmek için kayıt olmalısınız
    fadein: 20
    stay: 600
    fadeout: 20
  login:
    title: §9/login §cşifre
    subtitle: Lütfen giriş yapınız
    fadein: 20
    stay: 600
    fadeout: 20
  loginsuccess:
    title: Giriş Başarılı
    subtitle: İyi Oyunlar
    fadein: 20
    stay: 80
    fadeout: 20