passwords:
titles:
  join:
    title: §aSunucuya Hoş Geldiniz
    subtitle: §cplay§r.§boceanmonster§r.§cnet
    fadein: 20
    stay: 20
    fadeout: 20
  register:
    title: §6/register §8şifre §7şifre
    subtitle: §dSunucuda oynayabilmek için §l§n§6kayıt§r§d olmalısınız
    fadein: 20
    stay: 600
    fadeout: 20
  login:
    title: §9/login §8şifre
    subtitle: §dLütfen §9§lgiriş§r§d yapınız
    fadein: 20
    stay: 600
    fadeout: 20
  loginsuccess:
    title: §0§kk§r§5Giriş §2Başarılı§0§kk§r
    subtitle: §aİyi Oyunlar
    fadein: 20
    stay: 80
    fadeout: 20
kicktime: 1200