name: LoginRegister
version: ${project.version}
main: lakresmigo.loginregister.Loginregister
api-version: 1.16
authors: [ LAKRESMIGO ]
description: Login and Register Plugin
website: oceanmonster.net
commands:
  login:
    aliases:
      - girişyap
      - girisyap
    usage: /login şifre
    permission: login
  register:
    aliases:
      - kayıtol
      - kayitol
    usage: /register şifre şifretekrar
    permission: register
  settitle:
    aliases:
      - başlıkayarla
    permission: titlemanager
permissions:
  login:
    description: permission for login command
    default: true
  register:
    description: permission for register command
    default: true
  loggedin:
    description: permisson for enabling/disabling restrictions
    default: false
  titlemanager:
    default: op