name: LoginRegister
version: ${project.version}
main: lakresmigo.loginregister.Loginregister
api-version: 1.16
authors: [ LAKRESMIGO ]
description: Login and Register Plugin
website: oceanmonster.net
commands:
  login:
    aliases:
      - girişyap
      - girisyap
    usage: /login şifre
  register:
    aliases:
      - kayıtol
      - kayitol
    usage: /register şifre şifretekrar